version: '3'
services:
  app:
    env_file: '.env'
    ports:
      - "${PORT}:${PORT}"
    build:
      context: services/app
      dockerfile: Dockerfile.development
    volumes:
     - "~/.bash_history:/.bash_history"
     - "./services/app:/app:cached"
    depends_on:
     - db
  db:
    image: "postgres:latest"
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
     - "./services/nginx/app.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:8080"

