---
- hosts: all

  pre_tasks:
    - apt:
        update_cache: true
        name: "{{ item }}"
      with_items:
        - python3-pip
      become: true

    - block:
      - name: generate locale
        locale_gen:
          name: en_US.UTF-8
        tags: [locale]

      - name: set locale
        become: true
        shell: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8
        tags: [locale]

      - meta: reset_connection
    - pip:
        name:
          - docker-py
      tags: setup-docker
      become: true

  post_tasks:
    - user:
        name: "{{ workshop_run_user }}"
        groups: docker
        append: true
      become: true

    - meta: reset_connection
